org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=false

cfProjectID     = 579177
mcVersion       = 1.19.2
localVersion    = 1.1.0
mappingsChannel = official
mappingsVersion = 1.19.2
forgeVersion    = 43.2.8
# 1.19.2-PE1.1.0
projecteVersion = 4860858
curiosVersion   = 1.19.2-5.1.1.0
# 1.19.2-v1.5.1
ncrVersion = 4082456
jeiVersion = 11.4.0.285
# 1.19.2-1.0.1
pipezVersion = 4064952
# 12.9.2
ae2Version = 4293558
# 2.0.0
itankVersion = 3921315
# 8.3.103
clothVersion = 4633416
# 1.19.2-0.3.0.148
baVersion = 4276529
# 1.19.1-forge-8.9.2
jadeApiVersion=4914106
jadeVersion=4914105
topVersion=1.19-6.2.0-6
# 5.24.0
wthitVersion=5208194
# 0.2.3
badPacketsVersion=4784364