blank_issues_enabled: false
contact_links:
  - name: Wiki Pages
    url: https://github.com/WJXhhh/Project-Expansion-Arcanum/wiki
    about: Go here for information about how to use things in the mod.
